/* Generated by Yosys 0.66+105 (git sha1 72f6df873, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* top =  1  *)
(* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:3.1-98.10" *)
module uart(sys_clk, sys_rst_l, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:17.9-17.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:18.9-18.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:19.10-19.25" *)
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:20.9-20.14" *)
  input xmitH;
  wire xmitH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:21.13-21.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:22.10-22.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:24.9-24.23" *)
  input uart_REC_dataH;
  wire uart_REC_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:25.14-25.23" *)
  output [7:0] rec_dataH;
  reg [7:0] rec_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:26.10-26.20" *)
  output rec_readyH;
  wire rec_readyH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:57.1-60.43" *)
  wire _000_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:57.1-60.43" *)
  wire _001_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:57.1-60.43" *)
  wire _002_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:57.1-60.43" *)
  wire _003_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:71.1-74.42" *)
  wire _004_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:71.1-74.42" *)
  wire _005_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:71.1-74.42" *)
  wire _006_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:71.1-74.42" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:30.17-30.21" *)
  wire cntr;
  (* hdlname = "iRECEIVER bitCell_cntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:31.12-31.25" *)
  reg [3:0] \iRECEIVER.bitCell_cntrH ;
  (* hdlname = "iRECEIVER countH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:36.8-36.14" *)
  wire \iRECEIVER.countH ;
  (* hdlname = "iRECEIVER next_state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:29.12-29.22" *)
  wire [2:0] \iRECEIVER.next_state ;
  (* hdlname = "iRECEIVER par_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:33.12-33.21" *)
  reg [7:0] \iRECEIVER.par_dataH ;
  (* hdlname = "iRECEIVER rec_datH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:30.8-30.16" *)
  reg \iRECEIVER.rec_datH ;
  (* hdlname = "iRECEIVER rec_datSyncH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:30.18-30.30" *)
  reg \iRECEIVER.rec_datSyncH ;
  (* hdlname = "iRECEIVER rec_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:24.14-24.23" *)
  wire [7:0] \iRECEIVER.rec_dataH ;
  (* hdlname = "iRECEIVER rec_readyH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:25.10-25.20" *)
  reg \iRECEIVER.rec_readyH ;
  (* hdlname = "iRECEIVER rec_readyInH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:39.8-39.20" *)
  wire \iRECEIVER.rec_readyInH ;
  (* hdlname = "iRECEIVER recd_bitCntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:35.12-35.25" *)
  reg [3:0] \iRECEIVER.recd_bitCntrH ;
  (* hdlname = "iRECEIVER shiftH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:34.8-34.14" *)
  wire \iRECEIVER.shiftH ;
  (* hdlname = "iRECEIVER state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:29.24-29.29" *)
  reg [2:0] \iRECEIVER.state ;
  (* hdlname = "iRECEIVER sys_clk" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:20.9-20.16" *)
  wire \iRECEIVER.sys_clk ;
  (* hdlname = "iRECEIVER sys_rst_l" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:19.9-19.18" *)
  wire \iRECEIVER.sys_rst_l ;
  (* hdlname = "iRECEIVER uart_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:22.9-22.19" *)
  wire \iRECEIVER.uart_dataH ;
  (* hdlname = "iXMIT bitCell_cntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:28.12-28.25" *)
  wire [3:0] \iXMIT.bitCell_cntrH ;
  (* hdlname = "iXMIT bitCountH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:31.12-31.21" *)
  wire [3:0] \iXMIT.bitCountH ;
  (* hdlname = "iXMIT next_state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:25.12-25.22" *)
  wire [2:0] \iXMIT.next_state ;
  (* hdlname = "iXMIT state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:25.24-25.29" *)
  reg [2:0] \iXMIT.state ;
  (* hdlname = "iXMIT sys_clk" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:15.9-15.16" *)
  wire \iXMIT.sys_clk ;
  (* hdlname = "iXMIT sys_rst_l" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:16.9-16.18" *)
  wire \iXMIT.sys_rst_l ;
  (* hdlname = "iXMIT uart_xmitH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:18.10-18.20" *)
  wire \iXMIT.uart_xmitH ;
  (* hdlname = "iXMIT xmitH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:19.9-19.14" *)
  wire \iXMIT.xmitH ;
  (* hdlname = "iXMIT xmit_ShiftRegH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:30.12-30.26" *)
  wire [7:0] \iXMIT.xmit_ShiftRegH ;
  (* hdlname = "iXMIT xmit_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:20.13-20.23" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \iXMIT.xmit_dataH ;
  (* hdlname = "iXMIT xmit_doneH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:21.10-21.20" *)
  reg \iXMIT.xmit_doneH ;
  (* hdlname = "iXMIT xmit_doneInH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:36.8-36.20" *)
  wire \iXMIT.xmit_doneInH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:31.17-31.30" *)
  wire [7:0] rec_dataH_rec;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:29.17-29.31" *)
  reg [7:0] rec_dataH_temp;
  assign _010_ = \iRECEIVER.state [1] & ~(\iRECEIVER.state [2]);
  assign _011_ = _010_ & ~(\iRECEIVER.state [0]);
  assign _012_ = \iRECEIVER.state [0] & ~(\iRECEIVER.state [1]);
  assign _013_ = _012_ & ~(\iRECEIVER.state [2]);
  assign _014_ = ~(_011_ | _013_);
  assign _015_ = \iRECEIVER.rec_datH  | _014_;
  assign _016_ = \iRECEIVER.bitCell_cntrH [2] & ~(\iRECEIVER.bitCell_cntrH [0]);
  assign _017_ = \iRECEIVER.bitCell_cntrH [1] & \iRECEIVER.bitCell_cntrH [3];
  assign _018_ = _016_ & _017_;
  assign _019_ = \iRECEIVER.state [0] & _010_;
  assign _020_ = _018_ | ~(_019_);
  assign _021_ = ~(\iRECEIVER.bitCell_cntrH [0] | \iRECEIVER.bitCell_cntrH [1]);
  assign _022_ = \iRECEIVER.bitCell_cntrH [2] & ~(\iRECEIVER.bitCell_cntrH [3]);
  assign _023_ = ~(_021_ & _022_);
  assign _024_ = ~(_011_ & _023_);
  assign _025_ = \iRECEIVER.state [2] & ~(\iRECEIVER.state [1]);
  assign \iRECEIVER.countH  = _025_ & ~(\iRECEIVER.state [0]);
  assign _026_ = _024_ & ~(\iRECEIVER.countH );
  assign _027_ = _015_ & _026_;
  assign \iRECEIVER.next_state [1] = ~(_020_ & _027_);
  assign _028_ = _011_ & ~(_023_);
  assign _029_ = ~(\iRECEIVER.countH  | _028_);
  assign _030_ = ~(\iRECEIVER.recd_bitCntrH [0] | \iRECEIVER.recd_bitCntrH [1]);
  assign _031_ = \iRECEIVER.recd_bitCntrH [3] & ~(\iRECEIVER.recd_bitCntrH [2]);
  assign _032_ = _030_ & _031_;
  assign _033_ = ~(_019_ & _032_);
  assign _034_ = \iRECEIVER.state [2] | \iRECEIVER.rec_datH ;
  assign \iRECEIVER.rec_readyInH  = _012_ & _034_;
  assign _035_ = _020_ & ~(\iRECEIVER.rec_readyInH );
  assign _036_ = _033_ & _035_;
  assign \iRECEIVER.next_state [0] = ~(_029_ & _036_);
  assign _037_ = \iXMIT.state [2] | ~(\iXMIT.state [1]);
  assign _038_ = ~(\iXMIT.state [0] | \iXMIT.state [1]);
  assign _039_ = \iXMIT.state [2] | xmitH;
  assign _040_ = ~(_038_ & _039_);
  assign \iXMIT.next_state [1] = ~(_037_ & _040_);
  assign _041_ = \iRECEIVER.recd_bitCntrH [0] & \iRECEIVER.recd_bitCntrH [1];
  assign _042_ = ~(\iRECEIVER.recd_bitCntrH [2] & _041_);
  assign _043_ = \iRECEIVER.recd_bitCntrH [2] | _041_;
  assign _044_ = \iRECEIVER.countH  & _043_;
  assign _006_ = _042_ & _044_;
  assign _045_ = ~(_030_ | _041_);
  assign _005_ = \iRECEIVER.countH  & _045_;
  assign _004_ = \iRECEIVER.countH  & ~(\iRECEIVER.recd_bitCntrH [0]);
  assign \iRECEIVER.next_state [2] = _018_ & _019_;
  assign _046_ = \iRECEIVER.rec_datH  & _013_;
  assign _008_ = \iRECEIVER.countH  | _046_;
  assign _047_ = ~(_012_ | \iRECEIVER.next_state [2]);
  assign _048_ = _029_ & _047_;
  assign _049_ = \iRECEIVER.bitCell_cntrH [0] & \iRECEIVER.bitCell_cntrH [1];
  assign _050_ = ~(\iRECEIVER.bitCell_cntrH [2] & _049_);
  assign _051_ = \iRECEIVER.bitCell_cntrH [2] ^ _049_;
  assign _002_ = _048_ & _051_;
  assign _052_ = ~(_021_ | _049_);
  assign _001_ = _048_ & _052_;
  assign _053_ = ~(\iRECEIVER.recd_bitCntrH [3] ^ _042_);
  assign _007_ = \iRECEIVER.countH  & _053_;
  assign _000_ = _048_ & ~(\iRECEIVER.bitCell_cntrH [0]);
  assign _054_ = ~(\iRECEIVER.bitCell_cntrH [3] ^ _050_);
  assign _003_ = _048_ & _054_;
  assign _055_ = \iXMIT.state [2] & ~(\iXMIT.state [1]);
  assign _056_ = \iXMIT.state [0] & ~(_037_);
  assign \iXMIT.next_state [0] = _055_ | _056_;
  assign \iXMIT.next_state [2] = \iXMIT.state [0] & _055_;
  assign _009_ = _038_ & ~(\iXMIT.state [2]);
  assign uart_XMIT_dataH = \iXMIT.next_state [2] | _009_;
  assign \iXMIT.xmit_doneInH  = _038_ & ~(_039_);
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:71.1-74.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [0] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [0] <= _004_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:71.1-74.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [1] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [1] <= _005_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:71.1-74.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [2] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [2] <= _006_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:71.1-74.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [3] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [3] <= _007_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:63.1-68.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [0] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [0] <= \iRECEIVER.par_dataH [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:63.1-68.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [1] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [1] <= \iRECEIVER.par_dataH [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:63.1-68.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [2] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [2] <= \iRECEIVER.par_dataH [3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:63.1-68.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [3] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [3] <= \iRECEIVER.par_dataH [4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:63.1-68.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [4] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [4] <= \iRECEIVER.par_dataH [5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:63.1-68.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [5] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [5] <= \iRECEIVER.par_dataH [6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:63.1-68.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [6] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [6] <= \iRECEIVER.par_dataH [7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:57.1-60.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [0] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [0] <= _000_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:57.1-60.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [1] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [1] <= _001_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:57.1-60.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [2] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [2] <= _002_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:57.1-60.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [3] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [3] <= _003_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:47.1-54.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_datSyncH  <= 1'h1;
    else \iRECEIVER.rec_datSyncH  <= uart_REC_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:172.1-174.35" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.xmit_doneH  <= 1'h0;
    else \iXMIT.xmit_doneH  <= \iXMIT.xmit_doneInH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:73.1-75.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [0] <= 1'h0;
    else \iXMIT.state [0] <= \iXMIT.next_state [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:73.1-75.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [1] <= 1'h0;
    else \iXMIT.state [1] <= \iXMIT.next_state [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_xmit.v:73.1-75.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [2] <= 1'h0;
    else \iXMIT.state [2] <= \iXMIT.next_state [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:68.1-78.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[0] <= 1'h0;
    else rec_dataH_temp[0] <= \iRECEIVER.par_dataH [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:68.1-78.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[1] <= 1'h0;
    else rec_dataH_temp[1] <= \iRECEIVER.par_dataH [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:68.1-78.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[2] <= 1'h0;
    else rec_dataH_temp[2] <= \iRECEIVER.par_dataH [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:68.1-78.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[3] <= 1'h0;
    else rec_dataH_temp[3] <= \iRECEIVER.par_dataH [3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:68.1-78.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[4] <= 1'h0;
    else rec_dataH_temp[4] <= \iRECEIVER.par_dataH [4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:68.1-78.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[5] <= 1'h0;
    else rec_dataH_temp[5] <= \iRECEIVER.par_dataH [5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:68.1-78.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[6] <= 1'h0;
    else rec_dataH_temp[6] <= \iRECEIVER.par_dataH [6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:68.1-78.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[7] <= 1'h0;
    else rec_dataH_temp[7] <= \iRECEIVER.par_dataH [7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:58.1-65.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[0] <= 1'h0;
    else rec_dataH[0] <= rec_dataH_temp[0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:58.1-65.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[1] <= 1'h0;
    else rec_dataH[1] <= rec_dataH_temp[1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:58.1-65.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[2] <= 1'h0;
    else rec_dataH[2] <= rec_dataH_temp[2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:58.1-65.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[3] <= 1'h0;
    else rec_dataH[3] <= rec_dataH_temp[3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:58.1-65.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[4] <= 1'h0;
    else rec_dataH[4] <= rec_dataH_temp[4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:58.1-65.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[5] <= 1'h0;
    else rec_dataH[5] <= rec_dataH_temp[5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:58.1-65.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[6] <= 1'h0;
    else rec_dataH[6] <= rec_dataH_temp[6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\uart.v:58.1-65.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[7] <= 1'h0;
    else rec_dataH[7] <= rec_dataH_temp[7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:158.1-160.35" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_readyH  <= 1'h0;
    else \iRECEIVER.rec_readyH  <= \iRECEIVER.rec_readyInH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:63.1-68.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [7] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [7] <= \iRECEIVER.rec_datH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:47.1-54.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_datH  <= 1'h1;
    else \iRECEIVER.rec_datH  <= \iRECEIVER.rec_datSyncH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:79.1-81.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [0] <= 1'h1;
    else \iRECEIVER.state [0] <= \iRECEIVER.next_state [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:79.1-81.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [1] <= 1'h0;
    else \iRECEIVER.state [1] <= \iRECEIVER.next_state [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmplgud6ysn\\u_rec.v:79.1-81.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [2] <= 1'h0;
    else \iRECEIVER.state [2] <= \iRECEIVER.next_state [2];
  assign \iRECEIVER.sys_rst_l  = sys_rst_l;
  assign \iRECEIVER.sys_clk  = sys_clk;
  assign \iRECEIVER.uart_dataH  = uart_REC_dataH;
  assign \iRECEIVER.rec_dataH  = \iRECEIVER.par_dataH ;
  assign \iRECEIVER.shiftH  = \iRECEIVER.countH ;
  assign \iXMIT.sys_clk  = sys_clk;
  assign \iXMIT.sys_rst_l  = sys_rst_l;
  assign \iXMIT.uart_xmitH  = uart_XMIT_dataH;
  assign \iXMIT.xmitH  = xmitH;
  assign \iXMIT.xmit_dataH  = xmit_dataH;
  assign \iXMIT.bitCell_cntrH  = 4'h0;
  assign \iXMIT.xmit_ShiftRegH  = 8'h00;
  assign \iXMIT.bitCountH  = 4'h0;
  assign rec_dataH_rec = \iRECEIVER.par_dataH ;
  assign cntr = 1'h0;
  assign rec_readyH = \iRECEIVER.rec_readyH ;
  assign xmit_doneH = \iXMIT.xmit_doneH ;
endmodule
