/* Generated by Yosys 0.66+105 (git sha1 72f6df873, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* top =  1  *)
(* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:3.1-78.10" *)
module uart(sys_clk, sys_rst_l, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:19.9-19.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:20.9-20.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:23.10-23.25" *)
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:24.9-24.14" *)
  input xmitH;
  wire xmitH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:25.13-25.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:26.10-26.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:28.9-28.23" *)
  input uart_REC_dataH;
  wire uart_REC_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:29.14-29.23" *)
  output [7:0] rec_dataH;
  reg [7:0] rec_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:30.10-30.20" *)
  output rec_readyH;
  wire rec_readyH;
  wire _000_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:58.1-61.43" *)
  wire _001_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:58.1-61.43" *)
  wire _002_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:58.1-61.43" *)
  wire _003_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:58.1-61.43" *)
  wire _004_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:72.1-75.42" *)
  wire _005_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:72.1-75.42" *)
  wire _006_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:72.1-75.42" *)
  wire _007_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:72.1-75.42" *)
  wire _008_;
  wire _009_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:184.3-221.6" *)
  wire _010_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:184.3-221.6" *)
  wire _011_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:184.3-221.6" *)
  wire _012_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:223.1-229.30" *)
  wire _013_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:183.14-183.36" *)
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  (* hdlname = "iRECEIVER bitCell_cntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:32.12-32.25" *)
  reg [3:0] \iRECEIVER.bitCell_cntrH ;
  (* hdlname = "iRECEIVER countH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:37.8-37.14" *)
  wire \iRECEIVER.countH ;
  (* hdlname = "iRECEIVER next_state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:30.12-30.22" *)
  wire [2:0] \iRECEIVER.next_state ;
  (* hdlname = "iRECEIVER par_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:34.12-34.21" *)
  reg [7:0] \iRECEIVER.par_dataH ;
  (* hdlname = "iRECEIVER rec_datH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:31.8-31.16" *)
  reg \iRECEIVER.rec_datH ;
  (* hdlname = "iRECEIVER rec_datSyncH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:31.18-31.30" *)
  reg \iRECEIVER.rec_datSyncH ;
  (* hdlname = "iRECEIVER rec_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:25.14-25.23" *)
  wire [7:0] \iRECEIVER.rec_dataH ;
  (* hdlname = "iRECEIVER rec_readyH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:26.10-26.20" *)
  reg \iRECEIVER.rec_readyH ;
  (* hdlname = "iRECEIVER rec_readyInH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:40.8-40.20" *)
  wire \iRECEIVER.rec_readyInH ;
  (* hdlname = "iRECEIVER recd_bitCntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:36.12-36.25" *)
  reg [3:0] \iRECEIVER.recd_bitCntrH ;
  (* hdlname = "iRECEIVER shiftH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:35.8-35.14" *)
  wire \iRECEIVER.shiftH ;
  (* hdlname = "iRECEIVER state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:30.24-30.29" *)
  reg [2:0] \iRECEIVER.state ;
  (* hdlname = "iRECEIVER sys_clk" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:21.9-21.16" *)
  wire \iRECEIVER.sys_clk ;
  (* hdlname = "iRECEIVER sys_rst_l" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:20.9-20.18" *)
  wire \iRECEIVER.sys_rst_l ;
  (* hdlname = "iRECEIVER uart_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:23.9-23.19" *)
  wire \iRECEIVER.uart_dataH ;
  (* hdlname = "iXMIT DataSend_ena" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:40.16-40.28" *)
  reg \iXMIT.DataSend_ena ;
  (* hdlname = "iXMIT bitCell_cntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:29.12-29.25" *)
  wire [3:0] \iXMIT.bitCell_cntrH ;
  (* hdlname = "iXMIT bitCountH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:32.12-32.21" *)
  wire [3:0] \iXMIT.bitCountH ;
  (* hdlname = "iXMIT next_state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:26.12-26.22" *)
  wire [2:0] \iXMIT.next_state ;
  (* hdlname = "iXMIT state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:26.24-26.29" *)
  reg [2:0] \iXMIT.state ;
  (* hdlname = "iXMIT state_DataSend" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:42.16-42.30" *)
  reg [2:0] \iXMIT.state_DataSend ;
  (* hdlname = "iXMIT sys_clk" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:16.9-16.16" *)
  wire \iXMIT.sys_clk ;
  (* hdlname = "iXMIT sys_rst_l" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:17.9-17.18" *)
  wire \iXMIT.sys_rst_l ;
  (* hdlname = "iXMIT uart_xmitH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:19.10-19.20" *)
  wire \iXMIT.uart_xmitH ;
  (* hdlname = "iXMIT xmitH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:20.9-20.14" *)
  wire \iXMIT.xmitH ;
  (* hdlname = "iXMIT xmit_ShiftRegH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:31.12-31.26" *)
  wire [7:0] \iXMIT.xmit_ShiftRegH ;
  (* hdlname = "iXMIT xmit_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:21.13-21.23" *)
  wire [7:0] \iXMIT.xmit_dataH ;
  (* hdlname = "iXMIT xmit_doneH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:22.10-22.20" *)
  reg \iXMIT.xmit_doneH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:34.17-34.30" *)
  wire [7:0] rec_dataH_rec;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:33.17-33.31" *)
  reg [7:0] rec_dataH_temp;
  assign _060_ = \iXMIT.state [2] & ~(\iXMIT.state [1]);
  assign _061_ = \iXMIT.state [1] & ~(\iXMIT.state [2]);
  assign _062_ = \iXMIT.state [0] & _061_;
  assign \iXMIT.next_state [0] = _060_ | _062_;
  assign _063_ = \iXMIT.state_DataSend [0] & \iXMIT.state_DataSend [1];
  assign _014_ = \iXMIT.state_DataSend [2] & _063_;
  assign _064_ = \iRECEIVER.bitCell_cntrH [3] & ~(\iRECEIVER.bitCell_cntrH [0]);
  assign _065_ = \iRECEIVER.bitCell_cntrH [1] & \iRECEIVER.bitCell_cntrH [2];
  assign _066_ = _064_ & _065_;
  assign _067_ = \iRECEIVER.state [1] & ~(\iRECEIVER.state [2]);
  assign _068_ = \iRECEIVER.state [0] & _067_;
  assign \iRECEIVER.next_state [2] = _066_ & _068_;
  assign _069_ = ~(\iRECEIVER.bitCell_cntrH [0] | \iRECEIVER.bitCell_cntrH [1]);
  assign _070_ = \iRECEIVER.bitCell_cntrH [2] & ~(\iRECEIVER.bitCell_cntrH [3]);
  assign _071_ = _069_ & _070_;
  assign _072_ = _067_ & ~(\iRECEIVER.state [0]);
  assign _073_ = ~(_071_ & _072_);
  assign _074_ = \iRECEIVER.state [2] & ~(\iRECEIVER.state [1]);
  assign \iRECEIVER.countH  = _074_ & ~(\iRECEIVER.state [0]);
  assign _075_ = \iRECEIVER.state [0] & ~(\iRECEIVER.state [1]);
  assign _076_ = _073_ & ~(\iRECEIVER.countH );
  assign _077_ = ~(\iRECEIVER.next_state [2] | _075_);
  assign _078_ = _076_ & _077_;
  assign _079_ = \iRECEIVER.bitCell_cntrH [0] & \iRECEIVER.bitCell_cntrH [1];
  assign _080_ = ~(\iRECEIVER.bitCell_cntrH [2] & _079_);
  assign _081_ = \iRECEIVER.bitCell_cntrH [2] ^ _079_;
  assign _003_ = _078_ & _081_;
  assign _082_ = ~(_069_ | _079_);
  assign _002_ = _078_ & _082_;
  assign _001_ = _078_ & ~(\iRECEIVER.bitCell_cntrH [0]);
  assign _000_ = _063_ | ~(\iXMIT.state_DataSend [2]);
  assign _083_ = \iRECEIVER.recd_bitCntrH [1] & \iRECEIVER.recd_bitCntrH [0];
  assign _084_ = ~(\iRECEIVER.recd_bitCntrH [2] & _083_);
  assign _085_ = \iRECEIVER.recd_bitCntrH [2] | _083_;
  assign _086_ = \iRECEIVER.countH  & _085_;
  assign _007_ = _084_ & _086_;
  assign _087_ = ~(\iRECEIVER.recd_bitCntrH [1] | \iRECEIVER.recd_bitCntrH [0]);
  assign _088_ = ~(_083_ | _087_);
  assign _006_ = \iRECEIVER.countH  & _088_;
  assign _005_ = \iRECEIVER.countH  & ~(\iRECEIVER.recd_bitCntrH [0]);
  assign _089_ = xmit_dataH[4] & xmit_dataH[0];
  assign _090_ = ~(xmit_dataH[5] | xmit_dataH[1]);
  assign _091_ = _089_ & _090_;
  assign _092_ = ~(xmit_dataH[6] | xmit_dataH[2]);
  assign _093_ = ~(xmit_dataH[7] | xmit_dataH[3]);
  assign _094_ = _092_ & _093_;
  assign _095_ = ~(_091_ & _094_);
  assign _015_ = ~(_014_ & _095_);
  assign _016_ = xmit_dataH[7] & xmit_dataH[1];
  assign _017_ = xmit_dataH[3] & _016_;
  assign _018_ = xmit_dataH[6] & xmit_dataH[2];
  assign _019_ = \iXMIT.state_DataSend [0] & ~(\iXMIT.state_DataSend [2]);
  assign _020_ = _018_ & _019_;
  assign _021_ = \iXMIT.state_DataSend [1] & xmit_dataH[5];
  assign _022_ = _089_ & _021_;
  assign _023_ = _020_ & _022_;
  assign _024_ = ~(_017_ & _023_);
  assign _012_ = ~(_015_ & _024_);
  assign _025_ = ~(xmit_dataH[4] | xmit_dataH[0]);
  assign _026_ = ~(\iXMIT.state_DataSend [2] | \iXMIT.state_DataSend [0]);
  assign _027_ = _025_ & _026_;
  assign _028_ = _094_ & _027_;
  assign _029_ = _090_ & _028_;
  assign _030_ = ~(\iXMIT.state_DataSend [1] & _029_);
  assign _031_ = _030_ & ~(_012_);
  assign _032_ = _093_ & ~(\iXMIT.state_DataSend [1]);
  assign _033_ = _091_ & _032_;
  assign _034_ = ~(_020_ & _033_);
  assign _011_ = ~(_031_ & _034_);
  assign _035_ = _066_ | ~(_068_);
  assign _036_ = _075_ & ~(\iRECEIVER.state [2]);
  assign _037_ = _071_ | ~(_072_);
  assign _038_ = ~(_072_ | _036_);
  assign _039_ = ~(\iRECEIVER.rec_datH  | _038_);
  assign _040_ = ~(\iRECEIVER.countH  | _039_);
  assign _041_ = _035_ & _037_;
  assign \iRECEIVER.next_state [1] = ~(_040_ & _041_);
  assign _042_ = xmit_dataH[5] & ~(\iXMIT.state_DataSend [1]);
  assign _043_ = _092_ & _042_;
  assign _044_ = _027_ & _043_;
  assign _045_ = ~(_017_ & _044_);
  assign _010_ = ~(_031_ & _045_);
  assign _046_ = \iRECEIVER.recd_bitCntrH [3] & ~(\iRECEIVER.recd_bitCntrH [2]);
  assign _047_ = _087_ & _046_;
  assign _048_ = ~(_068_ & _047_);
  assign _049_ = \iRECEIVER.rec_datH  | \iRECEIVER.state [2];
  assign \iRECEIVER.rec_readyInH  = _075_ & _049_;
  assign _050_ = _048_ & ~(\iRECEIVER.rec_readyInH );
  assign _051_ = _035_ & _050_;
  assign \iRECEIVER.next_state [0] = ~(_076_ & _051_);
  assign _052_ = \iRECEIVER.rec_datH  & _036_;
  assign _009_ = \iRECEIVER.countH  | _052_;
  assign _053_ = ~(\iXMIT.state [0] | \iXMIT.state [1]);
  assign _054_ = \iXMIT.state [2] | xmitH;
  assign _055_ = _053_ & _054_;
  assign \iXMIT.next_state [1] = _061_ | _055_;
  assign _056_ = ~(\iRECEIVER.recd_bitCntrH [3] ^ _084_);
  assign _008_ = \iRECEIVER.countH  & _056_;
  assign _057_ = ~(\iRECEIVER.bitCell_cntrH [3] ^ _080_);
  assign _004_ = _078_ & _057_;
  assign \iXMIT.next_state [2] = \iXMIT.state [0] & _060_;
  assign _058_ = \iXMIT.DataSend_ena  | ~(_053_);
  assign _013_ = ~(_054_ | _058_);
  assign _059_ = _053_ & ~(\iXMIT.state [2]);
  assign uart_XMIT_dataH = \iXMIT.next_state [2] | _059_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [5] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [5] <= \iRECEIVER.par_dataH [6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [6] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [6] <= \iRECEIVER.par_dataH [7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:58.1-61.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [0] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [0] <= _001_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:58.1-61.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [1] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [1] <= _002_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:58.1-61.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [2] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [2] <= _003_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:58.1-61.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [3] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [3] <= _004_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:48.1-55.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_datSyncH  <= 1'h1;
    else \iRECEIVER.rec_datSyncH  <= uart_REC_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:223.1-229.30" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.xmit_doneH  <= 1'h0;
    else \iXMIT.xmit_doneH  <= _013_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:85.1-87.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [0] <= 1'h0;
    else \iXMIT.state [0] <= \iXMIT.next_state [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:85.1-87.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [1] <= 1'h0;
    else \iXMIT.state [1] <= \iXMIT.next_state [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:85.1-87.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [2] <= 1'h0;
    else \iXMIT.state [2] <= \iXMIT.next_state [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:184.3-221.6" *)
  always @(posedge xmitH, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state_DataSend [0] <= 1'h0;
    else if (_000_) \iXMIT.state_DataSend [0] <= _010_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:184.3-221.6" *)
  always @(posedge xmitH, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state_DataSend [1] <= 1'h0;
    else if (_000_) \iXMIT.state_DataSend [1] <= _011_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:184.3-221.6" *)
  always @(posedge xmitH, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state_DataSend [2] <= 1'h0;
    else if (_000_) \iXMIT.state_DataSend [2] <= _012_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_xmit.v:181.3-183.58" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.DataSend_ena  <= 1'h0;
    else if (_014_) \iXMIT.DataSend_ena  <= 1'h1;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[0] <= 1'h0;
    else rec_dataH_temp[0] <= \iRECEIVER.par_dataH [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[1] <= 1'h0;
    else rec_dataH_temp[1] <= \iRECEIVER.par_dataH [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[2] <= 1'h0;
    else rec_dataH_temp[2] <= \iRECEIVER.par_dataH [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[3] <= 1'h0;
    else rec_dataH_temp[3] <= \iRECEIVER.par_dataH [3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[4] <= 1'h0;
    else rec_dataH_temp[4] <= \iRECEIVER.par_dataH [4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[5] <= 1'h0;
    else rec_dataH_temp[5] <= \iRECEIVER.par_dataH [5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[6] <= 1'h0;
    else rec_dataH_temp[6] <= \iRECEIVER.par_dataH [6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[7] <= 1'h0;
    else rec_dataH_temp[7] <= \iRECEIVER.par_dataH [7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[0] <= 1'h0;
    else rec_dataH[0] <= rec_dataH_temp[0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[1] <= 1'h0;
    else rec_dataH[1] <= rec_dataH_temp[1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[2] <= 1'h0;
    else rec_dataH[2] <= rec_dataH_temp[2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[3] <= 1'h0;
    else rec_dataH[3] <= rec_dataH_temp[3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[4] <= 1'h0;
    else rec_dataH[4] <= rec_dataH_temp[4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[5] <= 1'h0;
    else rec_dataH[5] <= rec_dataH_temp[5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[6] <= 1'h0;
    else rec_dataH[6] <= rec_dataH_temp[6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[7] <= 1'h0;
    else rec_dataH[7] <= rec_dataH_temp[7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:158.1-160.35" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_readyH  <= 1'h0;
    else \iRECEIVER.rec_readyH  <= \iRECEIVER.rec_readyInH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [7] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [7] <= \iRECEIVER.rec_datH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:48.1-55.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_datH  <= 1'h1;
    else \iRECEIVER.rec_datH  <= \iRECEIVER.rec_datSyncH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:80.1-82.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [0] <= 1'h1;
    else \iRECEIVER.state [0] <= \iRECEIVER.next_state [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:80.1-82.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [1] <= 1'h0;
    else \iRECEIVER.state [1] <= \iRECEIVER.next_state [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:80.1-82.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [2] <= 1'h0;
    else \iRECEIVER.state [2] <= \iRECEIVER.next_state [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:72.1-75.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [0] <= 1'h0;
    else if (_009_) \iRECEIVER.recd_bitCntrH [0] <= _005_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:72.1-75.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [1] <= 1'h0;
    else if (_009_) \iRECEIVER.recd_bitCntrH [1] <= _006_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:72.1-75.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [2] <= 1'h0;
    else if (_009_) \iRECEIVER.recd_bitCntrH [2] <= _007_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:72.1-75.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [3] <= 1'h0;
    else if (_009_) \iRECEIVER.recd_bitCntrH [3] <= _008_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [0] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [0] <= \iRECEIVER.par_dataH [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [1] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [1] <= \iRECEIVER.par_dataH [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [2] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [2] <= \iRECEIVER.par_dataH [3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [3] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [3] <= \iRECEIVER.par_dataH [4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmppga2edyv\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [4] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [4] <= \iRECEIVER.par_dataH [5];
  assign \iRECEIVER.sys_rst_l  = sys_rst_l;
  assign \iRECEIVER.sys_clk  = sys_clk;
  assign \iRECEIVER.uart_dataH  = uart_REC_dataH;
  assign \iRECEIVER.rec_dataH  = \iRECEIVER.par_dataH ;
  assign \iRECEIVER.shiftH  = \iRECEIVER.countH ;
  assign \iXMIT.sys_clk  = sys_clk;
  assign \iXMIT.sys_rst_l  = sys_rst_l;
  assign \iXMIT.uart_xmitH  = uart_XMIT_dataH;
  assign \iXMIT.xmitH  = xmitH;
  assign \iXMIT.xmit_dataH  = xmit_dataH;
  assign \iXMIT.bitCell_cntrH  = 4'h0;
  assign \iXMIT.xmit_ShiftRegH  = 8'h00;
  assign \iXMIT.bitCountH  = 4'h0;
  assign rec_dataH_rec = \iRECEIVER.par_dataH ;
  assign rec_readyH = \iRECEIVER.rec_readyH ;
  assign xmit_doneH = \iXMIT.xmit_doneH ;
endmodule
