/* Generated by Yosys 0.66+105 (git sha1 72f6df873, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* top =  1  *)
(* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:3.1-78.10" *)
module uart(sys_clk, sys_rst_l, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:19.9-19.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:20.9-20.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:23.10-23.25" *)
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:24.9-24.14" *)
  input xmitH;
  wire xmitH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:25.13-25.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:26.10-26.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:28.9-28.23" *)
  input uart_REC_dataH;
  wire uart_REC_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:29.14-29.23" *)
  output [7:0] rec_dataH;
  reg [7:0] rec_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:30.10-30.20" *)
  output rec_readyH;
  wire rec_readyH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:56.1-59.43" *)
  wire _000_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:56.1-59.43" *)
  wire _001_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:56.1-59.43" *)
  wire _002_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:56.1-59.43" *)
  wire _003_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:70.1-73.42" *)
  wire _004_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:70.1-73.42" *)
  wire _005_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:70.1-73.42" *)
  wire _006_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:70.1-73.42" *)
  wire _007_;
  wire _008_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:192.1-197.31" *)
  wire _009_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:185.18-185.40" *)
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:188.19-188.32|C:\\Users\\saher\\DOWNLO~1\\OSS-CA~1\\bin\\../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _090_;
  (* force_downto = 32'd1 *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:188.19-188.32|C:\\Users\\saher\\DOWNLO~1\\OSS-CA~1\\bin\\../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _091_;
  (* hdlname = "iRECEIVER bitCell_cntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:30.12-30.25" *)
  reg [3:0] \iRECEIVER.bitCell_cntrH ;
  (* hdlname = "iRECEIVER countH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:35.8-35.14" *)
  wire \iRECEIVER.countH ;
  (* hdlname = "iRECEIVER next_state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:28.12-28.22" *)
  wire [2:0] \iRECEIVER.next_state ;
  (* hdlname = "iRECEIVER par_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:32.12-32.21" *)
  reg [7:0] \iRECEIVER.par_dataH ;
  (* hdlname = "iRECEIVER rec_datH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:29.8-29.16" *)
  reg \iRECEIVER.rec_datH ;
  (* hdlname = "iRECEIVER rec_datSyncH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:29.18-29.30" *)
  reg \iRECEIVER.rec_datSyncH ;
  (* hdlname = "iRECEIVER rec_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:23.14-23.23" *)
  wire [7:0] \iRECEIVER.rec_dataH ;
  (* hdlname = "iRECEIVER rec_readyH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:24.10-24.20" *)
  reg \iRECEIVER.rec_readyH ;
  (* hdlname = "iRECEIVER rec_readyInH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:38.8-38.20" *)
  wire \iRECEIVER.rec_readyInH ;
  (* hdlname = "iRECEIVER recd_bitCntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:34.12-34.25" *)
  reg [3:0] \iRECEIVER.recd_bitCntrH ;
  (* hdlname = "iRECEIVER shiftH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:33.8-33.14" *)
  wire \iRECEIVER.shiftH ;
  (* hdlname = "iRECEIVER state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:28.24-28.29" *)
  reg [2:0] \iRECEIVER.state ;
  (* hdlname = "iRECEIVER sys_clk" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:19.9-19.16" *)
  wire \iRECEIVER.sys_clk ;
  (* hdlname = "iRECEIVER sys_rst_l" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:18.9-18.18" *)
  wire \iRECEIVER.sys_rst_l ;
  (* hdlname = "iRECEIVER uart_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:21.9-21.19" *)
  wire \iRECEIVER.uart_dataH ;
  (* hdlname = "iXMIT DataSend_ena" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:40.16-40.28" *)
  reg \iXMIT.DataSend_ena ;
  (* hdlname = "iXMIT bitCell_cntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:29.12-29.25" *)
  wire [3:0] \iXMIT.bitCell_cntrH ;
  (* hdlname = "iXMIT bitCountH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:32.12-32.21" *)
  wire [3:0] \iXMIT.bitCountH ;
  (* hdlname = "iXMIT count_in" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:43.16-43.24" *)
  reg [31:0] \iXMIT.count_in ;
  (* hdlname = "iXMIT next_state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:26.12-26.22" *)
  wire [2:0] \iXMIT.next_state ;
  (* hdlname = "iXMIT state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:26.24-26.29" *)
  reg [2:0] \iXMIT.state ;
  (* hdlname = "iXMIT sys_clk" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:16.9-16.16" *)
  wire \iXMIT.sys_clk ;
  (* hdlname = "iXMIT sys_rst_l" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:17.9-17.18" *)
  wire \iXMIT.sys_rst_l ;
  (* hdlname = "iXMIT uart_xmitH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:19.10-19.20" *)
  wire \iXMIT.uart_xmitH ;
  (* hdlname = "iXMIT xmitH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:20.9-20.14" *)
  wire \iXMIT.xmitH ;
  (* hdlname = "iXMIT xmit_ShiftRegH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:31.12-31.26" *)
  wire [7:0] \iXMIT.xmit_ShiftRegH ;
  (* hdlname = "iXMIT xmit_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:21.13-21.23" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \iXMIT.xmit_dataH ;
  (* hdlname = "iXMIT xmit_doneH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:22.10-22.20" *)
  reg \iXMIT.xmit_doneH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:34.17-34.30" *)
  wire [7:0] rec_dataH_rec;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:33.17-33.31" *)
  reg [7:0] rec_dataH_temp;
  assign _090_[0] = ~\iXMIT.count_in [0];
  assign _011_ = \iXMIT.count_in [1] & \iXMIT.count_in [0];
  assign _012_ = \iXMIT.count_in [2] & _011_;
  assign _013_ = \iXMIT.count_in [3] & _012_;
  assign _014_ = \iXMIT.count_in [4] & _013_;
  assign _015_ = \iXMIT.count_in [5] & _014_;
  assign _016_ = \iXMIT.count_in [6] & _015_;
  assign _017_ = \iXMIT.count_in [7] & _016_;
  assign _018_ = \iXMIT.count_in [8] & _017_;
  assign _019_ = \iXMIT.count_in [9] & _018_;
  assign _020_ = \iXMIT.count_in [10] & _019_;
  assign _021_ = \iXMIT.count_in [11] & _020_;
  assign _022_ = \iXMIT.count_in [12] & _021_;
  assign _023_ = \iXMIT.count_in [13] & _022_;
  assign _024_ = \iXMIT.count_in [14] & _023_;
  assign _025_ = \iXMIT.count_in [15] & _024_;
  assign _026_ = \iXMIT.count_in [16] & _025_;
  assign _027_ = \iXMIT.count_in [17] & _026_;
  assign _028_ = \iXMIT.count_in [18] & _027_;
  assign _091_[18] = \iXMIT.count_in [18] ^ _027_;
  assign _091_[16] = \iXMIT.count_in [16] ^ _025_;
  assign _091_[17] = \iXMIT.count_in [17] ^ _026_;
  assign _029_ = \iXMIT.count_in [19] & _028_;
  assign _030_ = \iXMIT.count_in [20] & _029_;
  assign _031_ = \iXMIT.count_in [21] & _030_;
  assign _032_ = \iXMIT.count_in [22] & _031_;
  assign _033_ = \iXMIT.count_in [23] & _032_;
  assign _034_ = \iXMIT.count_in [24] & _033_;
  assign _035_ = \iXMIT.count_in [25] & _034_;
  assign _091_[25] = \iXMIT.count_in [25] ^ _034_;
  assign _091_[23] = \iXMIT.count_in [23] ^ _032_;
  assign _091_[5] = \iXMIT.count_in [5] ^ _014_;
  assign _091_[24] = \iXMIT.count_in [24] ^ _033_;
  assign _091_[20] = \iXMIT.count_in [20] ^ _029_;
  assign _091_[1] = \iXMIT.count_in [1] ^ \iXMIT.count_in [0];
  assign _091_[6] = \iXMIT.count_in [6] ^ _015_;
  assign _091_[4] = \iXMIT.count_in [4] ^ _013_;
  assign _091_[2] = \iXMIT.count_in [2] ^ _011_;
  assign _091_[13] = \iXMIT.count_in [13] ^ _022_;
  assign _036_ = \iXMIT.state [2] | ~(\iXMIT.state [1]);
  assign _037_ = ~(\iXMIT.state [1] | \iXMIT.state [0]);
  assign _038_ = \iXMIT.state [2] | xmitH;
  assign _039_ = ~(_037_ & _038_);
  assign \iXMIT.next_state [1] = ~(_036_ & _039_);
  assign _040_ = \iXMIT.count_in [26] & _035_;
  assign _041_ = \iXMIT.count_in [27] & _040_;
  assign _042_ = \iXMIT.count_in [28] & _041_;
  assign _043_ = \iXMIT.count_in [29] & _042_;
  assign _044_ = \iXMIT.count_in [30] & _043_;
  assign _010_ = \iXMIT.count_in [31] & _044_;
  assign _091_[31] = \iXMIT.count_in [31] ^ _044_;
  assign _045_ = \iXMIT.state [2] & ~(\iXMIT.state [1]);
  assign _046_ = \iXMIT.state [0] & ~(_036_);
  assign \iXMIT.next_state [0] = _045_ | _046_;
  assign _091_[15] = \iXMIT.count_in [15] ^ _024_;
  assign _091_[9] = \iXMIT.count_in [9] ^ _018_;
  assign _047_ = ~(\iRECEIVER.bitCell_cntrH [1] | \iRECEIVER.bitCell_cntrH [0]);
  assign _048_ = \iRECEIVER.bitCell_cntrH [2] & ~(\iRECEIVER.bitCell_cntrH [3]);
  assign _049_ = _047_ & _048_;
  assign _050_ = \iRECEIVER.state [1] & ~(\iRECEIVER.state [2]);
  assign _051_ = _050_ & ~(\iRECEIVER.state [0]);
  assign _052_ = ~(_049_ & _051_);
  assign _053_ = \iRECEIVER.state [2] & ~(\iRECEIVER.state [1]);
  assign \iRECEIVER.countH  = _053_ & ~(\iRECEIVER.state [0]);
  assign _054_ = _052_ & ~(\iRECEIVER.countH );
  assign _055_ = \iRECEIVER.state [0] & ~(\iRECEIVER.state [1]);
  assign _056_ = \iRECEIVER.bitCell_cntrH [3] & ~(\iRECEIVER.bitCell_cntrH [0]);
  assign _057_ = \iRECEIVER.bitCell_cntrH [1] & \iRECEIVER.bitCell_cntrH [2];
  assign _058_ = _056_ & _057_;
  assign _059_ = \iRECEIVER.state [0] & _050_;
  assign \iRECEIVER.next_state [2] = _058_ & _059_;
  assign _060_ = ~(_055_ | \iRECEIVER.next_state [2]);
  assign _061_ = _054_ & _060_;
  assign _062_ = \iRECEIVER.bitCell_cntrH [1] & \iRECEIVER.bitCell_cntrH [0];
  assign _063_ = ~(\iRECEIVER.bitCell_cntrH [2] & _062_);
  assign _064_ = \iRECEIVER.bitCell_cntrH [2] ^ _062_;
  assign _002_ = _061_ & _064_;
  assign _065_ = ~(_047_ | _062_);
  assign _001_ = _061_ & _065_;
  assign _000_ = _061_ & ~(\iRECEIVER.bitCell_cntrH [0]);
  assign _091_[12] = \iXMIT.count_in [12] ^ _021_;
  assign _091_[14] = \iXMIT.count_in [14] ^ _023_;
  assign _091_[26] = \iXMIT.count_in [26] ^ _035_;
  assign _066_ = \iRECEIVER.recd_bitCntrH [0] & \iRECEIVER.recd_bitCntrH [1];
  assign _067_ = ~(\iRECEIVER.recd_bitCntrH [2] & _066_);
  assign _068_ = \iRECEIVER.recd_bitCntrH [2] | _066_;
  assign _069_ = \iRECEIVER.countH  & _068_;
  assign _006_ = _067_ & _069_;
  assign _070_ = ~(\iRECEIVER.recd_bitCntrH [0] | \iRECEIVER.recd_bitCntrH [1]);
  assign _071_ = ~(_066_ | _070_);
  assign _005_ = \iRECEIVER.countH  & _071_;
  assign _004_ = \iRECEIVER.countH  & ~(\iRECEIVER.recd_bitCntrH [0]);
  assign _091_[28] = \iXMIT.count_in [28] ^ _041_;
  assign _091_[3] = \iXMIT.count_in [3] ^ _012_;
  assign _091_[27] = \iXMIT.count_in [27] ^ _040_;
  assign _091_[19] = \iXMIT.count_in [19] ^ _028_;
  assign _091_[21] = \iXMIT.count_in [21] ^ _030_;
  assign _091_[29] = \iXMIT.count_in [29] ^ _042_;
  assign _072_ = _058_ | ~(_059_);
  assign _073_ = _055_ & ~(\iRECEIVER.state [2]);
  assign _074_ = _049_ | ~(_051_);
  assign _075_ = _072_ & _074_;
  assign _076_ = ~(_051_ | _073_);
  assign _077_ = ~(\iRECEIVER.rec_datH  | _076_);
  assign _078_ = ~(\iRECEIVER.countH  | _077_);
  assign \iRECEIVER.next_state [1] = ~(_075_ & _078_);
  assign _091_[22] = \iXMIT.count_in [22] ^ _031_;
  assign _079_ = \iRECEIVER.rec_datH  | \iRECEIVER.state [2];
  assign \iRECEIVER.rec_readyInH  = _055_ & _079_;
  assign _080_ = _072_ & ~(\iRECEIVER.rec_readyInH );
  assign _081_ = \iRECEIVER.recd_bitCntrH [3] & ~(\iRECEIVER.recd_bitCntrH [2]);
  assign _082_ = _070_ & _081_;
  assign _083_ = ~(_059_ & _082_);
  assign _084_ = _080_ & _083_;
  assign \iRECEIVER.next_state [0] = ~(_054_ & _084_);
  assign _091_[7] = \iXMIT.count_in [7] ^ _016_;
  assign _091_[8] = \iXMIT.count_in [8] ^ _017_;
  assign _091_[10] = \iXMIT.count_in [10] ^ _019_;
  assign _091_[30] = \iXMIT.count_in [30] ^ _043_;
  assign _091_[11] = \iXMIT.count_in [11] ^ _020_;
  assign _085_ = \iRECEIVER.rec_datH  & _073_;
  assign _008_ = \iRECEIVER.countH  | _085_;
  assign _086_ = ~(\iRECEIVER.recd_bitCntrH [3] ^ _067_);
  assign _007_ = \iRECEIVER.countH  & _086_;
  assign _087_ = ~(\iRECEIVER.bitCell_cntrH [3] ^ _063_);
  assign _003_ = _061_ & _087_;
  assign \iXMIT.next_state [2] = \iXMIT.state [0] & _045_;
  assign _088_ = \iXMIT.DataSend_ena  | ~(_037_);
  assign _009_ = ~(_038_ | _088_);
  assign _089_ = _037_ & ~(\iXMIT.state [2]);
  assign uart_XMIT_dataH = \iXMIT.next_state [2] | _089_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [16] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [16] <= _091_[16];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [17] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [17] <= _091_[17];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [18] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [18] <= _091_[18];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [19] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [19] <= _091_[19];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [20] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [20] <= _091_[20];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [21] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [21] <= _091_[21];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [22] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [22] <= _091_[22];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [23] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [23] <= _091_[23];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [24] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [24] <= _091_[24];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [25] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [25] <= _091_[25];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [26] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [26] <= _091_[26];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [27] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [27] <= _091_[27];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [28] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [28] <= _091_[28];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [29] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [29] <= _091_[29];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [30] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [30] <= _091_[30];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [31] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [31] <= _091_[31];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:83.1-85.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [0] <= 1'h0;
    else \iXMIT.state [0] <= \iXMIT.next_state [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:83.1-85.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [1] <= 1'h0;
    else \iXMIT.state [1] <= \iXMIT.next_state [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:83.1-85.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [2] <= 1'h0;
    else \iXMIT.state [2] <= \iXMIT.next_state [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.DataSend_ena  <= 1'h0;
    else if (_010_) \iXMIT.DataSend_ena  <= 1'h1;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:192.1-197.31" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.xmit_doneH  <= 1'h0;
    else \iXMIT.xmit_doneH  <= _009_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[0] <= 1'h0;
    else rec_dataH_temp[0] <= \iRECEIVER.par_dataH [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[1] <= 1'h0;
    else rec_dataH_temp[1] <= \iRECEIVER.par_dataH [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[2] <= 1'h0;
    else rec_dataH_temp[2] <= \iRECEIVER.par_dataH [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[3] <= 1'h0;
    else rec_dataH_temp[3] <= \iRECEIVER.par_dataH [3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[4] <= 1'h0;
    else rec_dataH_temp[4] <= \iRECEIVER.par_dataH [4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[5] <= 1'h0;
    else rec_dataH_temp[5] <= \iRECEIVER.par_dataH [5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[6] <= 1'h0;
    else rec_dataH_temp[6] <= \iRECEIVER.par_dataH [6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:69.1-76.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[7] <= 1'h0;
    else rec_dataH_temp[7] <= \iRECEIVER.par_dataH [7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[0] <= 1'h0;
    else rec_dataH[0] <= rec_dataH_temp[0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[1] <= 1'h0;
    else rec_dataH[1] <= rec_dataH_temp[1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[2] <= 1'h0;
    else rec_dataH[2] <= rec_dataH_temp[2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[3] <= 1'h0;
    else rec_dataH[3] <= rec_dataH_temp[3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[4] <= 1'h0;
    else rec_dataH[4] <= rec_dataH_temp[4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[5] <= 1'h0;
    else rec_dataH[5] <= rec_dataH_temp[5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[6] <= 1'h0;
    else rec_dataH[6] <= rec_dataH_temp[6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[7] <= 1'h0;
    else rec_dataH[7] <= rec_dataH_temp[7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:156.1-158.35" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_readyH  <= 1'h0;
    else \iRECEIVER.rec_readyH  <= \iRECEIVER.rec_readyInH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:62.1-67.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [7] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [7] <= \iRECEIVER.rec_datH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:46.1-53.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_datH  <= 1'h1;
    else \iRECEIVER.rec_datH  <= \iRECEIVER.rec_datSyncH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:78.1-80.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [0] <= 1'h1;
    else \iRECEIVER.state [0] <= \iRECEIVER.next_state [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:78.1-80.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [1] <= 1'h0;
    else \iRECEIVER.state [1] <= \iRECEIVER.next_state [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:78.1-80.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [2] <= 1'h0;
    else \iRECEIVER.state [2] <= \iRECEIVER.next_state [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:70.1-73.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [0] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [0] <= _004_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:70.1-73.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [1] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [1] <= _005_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:70.1-73.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [2] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [2] <= _006_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:70.1-73.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [3] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [3] <= _007_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:62.1-67.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [0] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [0] <= \iRECEIVER.par_dataH [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:62.1-67.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [1] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [1] <= \iRECEIVER.par_dataH [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:62.1-67.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [2] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [2] <= \iRECEIVER.par_dataH [3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:62.1-67.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [3] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [3] <= \iRECEIVER.par_dataH [4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:62.1-67.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [4] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [4] <= \iRECEIVER.par_dataH [5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:62.1-67.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [5] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [5] <= \iRECEIVER.par_dataH [6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:62.1-67.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [6] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [6] <= \iRECEIVER.par_dataH [7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:56.1-59.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [0] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [0] <= _000_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:56.1-59.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [1] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [1] <= _001_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:56.1-59.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [2] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [2] <= _002_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:56.1-59.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [3] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [3] <= _003_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_rec.v:46.1-53.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_datSyncH  <= 1'h1;
    else \iRECEIVER.rec_datSyncH  <= uart_REC_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [0] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [0] <= _090_[0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [1] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [1] <= _091_[1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [2] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [2] <= _091_[2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [3] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [3] <= _091_[3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [4] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [4] <= _091_[4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [5] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [5] <= _091_[5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [6] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [6] <= _091_[6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [7] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [7] <= _091_[7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [8] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [8] <= _091_[8];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [9] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [9] <= _091_[9];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [10] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [10] <= _091_[10];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [11] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [11] <= _091_[11];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [12] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [12] <= _091_[12];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [13] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [13] <= _091_[13];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [14] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [14] <= _091_[14];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmph61eaud8\\u_xmit.v:181.3-189.8" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.count_in [15] <= 1'h0;
    else if (!_010_) \iXMIT.count_in [15] <= _091_[15];
  assign \iRECEIVER.sys_rst_l  = sys_rst_l;
  assign \iRECEIVER.sys_clk  = sys_clk;
  assign \iRECEIVER.uart_dataH  = uart_REC_dataH;
  assign \iRECEIVER.rec_dataH  = \iRECEIVER.par_dataH ;
  assign \iRECEIVER.shiftH  = \iRECEIVER.countH ;
  assign _090_[31:1] = \iXMIT.count_in [31:1];
  assign \iXMIT.sys_clk  = sys_clk;
  assign \iXMIT.sys_rst_l  = sys_rst_l;
  assign \iXMIT.uart_xmitH  = uart_XMIT_dataH;
  assign \iXMIT.xmitH  = xmitH;
  assign \iXMIT.xmit_dataH  = xmit_dataH;
  assign \iXMIT.bitCell_cntrH  = 4'h0;
  assign \iXMIT.xmit_ShiftRegH  = 8'h00;
  assign \iXMIT.bitCountH  = 4'h0;
  assign _091_[0] = _090_[0];
  assign rec_dataH_rec = \iRECEIVER.par_dataH ;
  assign rec_readyH = \iRECEIVER.rec_readyH ;
  assign xmit_doneH = \iXMIT.xmit_doneH ;
endmodule
