/* Generated by Yosys 0.66+105 (git sha1 72f6df873, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* top =  1  *)
(* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:8.1-89.10" *)
module uart(sys_clk, sys_rst_l, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:26.9-26.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:27.9-27.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:30.10-30.25" *)
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:31.9-31.14" *)
  input xmitH;
  wire xmitH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:32.13-32.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:33.10-33.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:36.9-36.23" *)
  input uart_REC_dataH;
  wire uart_REC_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:37.14-37.23" *)
  output [7:0] rec_dataH;
  reg [7:0] rec_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:38.10-38.20" *)
  output rec_readyH;
  wire rec_readyH;
  wire _000_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:58.1-61.43" *)
  wire _001_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:58.1-61.43" *)
  wire _002_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:58.1-61.43" *)
  wire _003_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:58.1-61.43" *)
  wire _004_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:72.1-75.42" *)
  wire _005_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:72.1-75.42" *)
  wire _006_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:72.1-75.42" *)
  wire _007_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:72.1-75.42" *)
  wire _008_;
  wire _009_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:193.3-230.6" *)
  wire _010_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:193.3-230.6" *)
  wire _011_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:193.3-230.6" *)
  wire _012_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:191.14-191.36" *)
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  (* hdlname = "iRECEIVER bitCell_cntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:32.12-32.25" *)
  reg [3:0] \iRECEIVER.bitCell_cntrH ;
  (* hdlname = "iRECEIVER countH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:37.8-37.14" *)
  wire \iRECEIVER.countH ;
  (* hdlname = "iRECEIVER next_state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:30.12-30.22" *)
  wire [2:0] \iRECEIVER.next_state ;
  (* hdlname = "iRECEIVER par_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:34.12-34.21" *)
  reg [7:0] \iRECEIVER.par_dataH ;
  (* hdlname = "iRECEIVER rec_datH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:31.8-31.16" *)
  reg \iRECEIVER.rec_datH ;
  (* hdlname = "iRECEIVER rec_datSyncH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:31.18-31.30" *)
  reg \iRECEIVER.rec_datSyncH ;
  (* hdlname = "iRECEIVER rec_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:25.14-25.23" *)
  wire [7:0] \iRECEIVER.rec_dataH ;
  (* hdlname = "iRECEIVER rec_readyH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:26.10-26.20" *)
  reg \iRECEIVER.rec_readyH ;
  (* hdlname = "iRECEIVER rec_readyInH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:40.8-40.20" *)
  wire \iRECEIVER.rec_readyInH ;
  (* hdlname = "iRECEIVER recd_bitCntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:36.12-36.25" *)
  reg [3:0] \iRECEIVER.recd_bitCntrH ;
  (* hdlname = "iRECEIVER shiftH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:35.8-35.14" *)
  wire \iRECEIVER.shiftH ;
  (* hdlname = "iRECEIVER state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:30.24-30.29" *)
  reg [2:0] \iRECEIVER.state ;
  (* hdlname = "iRECEIVER sys_clk" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:21.9-21.16" *)
  wire \iRECEIVER.sys_clk ;
  (* hdlname = "iRECEIVER sys_rst_l" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:20.9-20.18" *)
  wire \iRECEIVER.sys_rst_l ;
  (* hdlname = "iRECEIVER uart_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:23.9-23.19" *)
  wire \iRECEIVER.uart_dataH ;
  (* hdlname = "iXMIT DataSend_ena" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:39.16-39.28" *)
  reg \iXMIT.DataSend_ena ;
  (* hdlname = "iXMIT bitCell_cntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:29.12-29.25" *)
  wire [3:0] \iXMIT.bitCell_cntrH ;
  (* hdlname = "iXMIT bitCountH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:32.12-32.21" *)
  wire [3:0] \iXMIT.bitCountH ;
  (* hdlname = "iXMIT next_state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:26.12-26.22" *)
  wire [2:0] \iXMIT.next_state ;
  (* hdlname = "iXMIT state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:26.24-26.29" *)
  reg [2:0] \iXMIT.state ;
  (* hdlname = "iXMIT state_DataSend" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:40.16-40.30" *)
  reg [2:0] \iXMIT.state_DataSend ;
  (* hdlname = "iXMIT sys_clk" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:16.9-16.16" *)
  wire \iXMIT.sys_clk ;
  (* hdlname = "iXMIT sys_rst_l" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:17.9-17.18" *)
  wire \iXMIT.sys_rst_l ;
  (* hdlname = "iXMIT uart_xmitH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:19.10-19.20" *)
  wire \iXMIT.uart_xmitH ;
  (* hdlname = "iXMIT xmitH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:20.9-20.14" *)
  wire \iXMIT.xmitH ;
  (* hdlname = "iXMIT xmit_ShiftRegH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:31.12-31.26" *)
  wire [7:0] \iXMIT.xmit_ShiftRegH ;
  (* hdlname = "iXMIT xmit_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:21.13-21.23" *)
  wire [7:0] \iXMIT.xmit_dataH ;
  (* hdlname = "iXMIT xmit_doneH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:22.10-22.20" *)
  reg \iXMIT.xmit_doneH ;
  (* hdlname = "iXMIT xmit_doneInH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:37.8-37.20" *)
  wire \iXMIT.xmit_doneInH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:43.17-43.30" *)
  wire [7:0] rec_dataH_rec;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:42.17-42.31" *)
  reg [7:0] rec_dataH_temp;
  assign _073_ = ~\iXMIT.DataSend_ena ;
  assign _074_ = ~(\iXMIT.state [1] | \iXMIT.state [0]);
  assign _075_ = _074_ & ~(\iXMIT.state [2]);
  assign _076_ = ~(xmitH & _075_);
  assign _077_ = ~(\iXMIT.state [2] & _074_);
  assign _078_ = \iXMIT.DataSend_ena  | ~(\iXMIT.state [2]);
  assign _079_ = \iXMIT.state [1] & \iXMIT.state [0];
  assign _080_ = ~(_078_ & _079_);
  assign _081_ = _077_ & _080_;
  assign _082_ = \iXMIT.state [2] | ~(\iXMIT.state [1]);
  assign _083_ = \iXMIT.state [0] | _082_;
  assign _084_ = _081_ & _083_;
  assign \iXMIT.next_state [1] = ~(_076_ & _084_);
  assign _085_ = ~(\iXMIT.state [2] & \iXMIT.state [0]);
  assign _086_ = \iXMIT.state [1] | _085_;
  assign _087_ = _073_ | _083_;
  assign _088_ = _086_ & _087_;
  assign \iXMIT.next_state [0] = ~(_081_ & _088_);
  assign _089_ = ~(\iRECEIVER.bitCell_cntrH [1] | \iRECEIVER.bitCell_cntrH [0]);
  assign _090_ = \iRECEIVER.bitCell_cntrH [2] & ~(\iRECEIVER.bitCell_cntrH [3]);
  assign _091_ = _089_ & _090_;
  assign _092_ = \iRECEIVER.state [1] & ~(\iRECEIVER.state [2]);
  assign _093_ = _092_ & ~(\iRECEIVER.state [0]);
  assign _094_ = ~(_091_ & _093_);
  assign _095_ = \iRECEIVER.state [2] & ~(\iRECEIVER.state [1]);
  assign \iRECEIVER.countH  = _095_ & ~(\iRECEIVER.state [0]);
  assign _096_ = _094_ & ~(\iRECEIVER.countH );
  assign _097_ = \iRECEIVER.bitCell_cntrH [1] & ~(\iRECEIVER.bitCell_cntrH [0]);
  assign _098_ = \iRECEIVER.bitCell_cntrH [2] & \iRECEIVER.bitCell_cntrH [3];
  assign _099_ = _097_ & _098_;
  assign _100_ = \iRECEIVER.state [0] & _092_;
  assign \iRECEIVER.next_state [2] = _099_ & _100_;
  assign _101_ = \iRECEIVER.state [0] & ~(\iRECEIVER.state [1]);
  assign _102_ = ~(\iRECEIVER.next_state [2] | _101_);
  assign _103_ = _096_ & _102_;
  assign _104_ = \iRECEIVER.bitCell_cntrH [1] & \iRECEIVER.bitCell_cntrH [0];
  assign _105_ = ~(\iRECEIVER.bitCell_cntrH [2] & _104_);
  assign _106_ = \iRECEIVER.bitCell_cntrH [2] ^ _104_;
  assign _003_ = _103_ & _106_;
  assign _107_ = ~(_089_ | _104_);
  assign _002_ = _103_ & _107_;
  assign _001_ = _103_ & ~(\iRECEIVER.bitCell_cntrH [0]);
  assign _108_ = \iXMIT.state_DataSend [1] & \iXMIT.state_DataSend [0];
  assign _000_ = _108_ | ~(\iXMIT.state_DataSend [2]);
  assign _013_ = \iXMIT.state_DataSend [2] & _108_;
  assign _109_ = ~(xmit_dataH[6] | xmit_dataH[2]);
  assign _110_ = ~(xmit_dataH[3] | xmit_dataH[7]);
  assign _014_ = _109_ & _110_;
  assign _015_ = xmit_dataH[4] & xmit_dataH[0];
  assign _016_ = ~(xmit_dataH[5] | xmit_dataH[1]);
  assign _017_ = _015_ & _016_;
  assign _018_ = ~(_014_ & _017_);
  assign _019_ = ~(_013_ & _018_);
  assign _020_ = xmit_dataH[3] & xmit_dataH[2];
  assign _021_ = xmit_dataH[7] & _020_;
  assign _022_ = xmit_dataH[6] & xmit_dataH[5];
  assign _023_ = _108_ & _022_;
  assign _024_ = xmit_dataH[1] & ~(\iXMIT.state_DataSend [2]);
  assign _025_ = _015_ & _024_;
  assign _026_ = _023_ & _025_;
  assign _027_ = ~(_021_ & _026_);
  assign _012_ = ~(_019_ & _027_);
  assign _028_ = \iXMIT.state_DataSend [1] & ~(\iXMIT.state_DataSend [0]);
  assign _029_ = xmit_dataH[2] & _028_;
  assign _030_ = xmit_dataH[6] & ~(\iXMIT.state_DataSend [2]);
  assign _031_ = _110_ & _030_;
  assign _032_ = _029_ & _031_;
  assign _033_ = ~(_017_ & _032_);
  assign _034_ = _033_ & ~(_012_);
  assign _035_ = \iXMIT.state_DataSend [0] & ~(xmit_dataH[4]);
  assign _036_ = _035_ & ~(xmit_dataH[0]);
  assign _037_ = ~(\iXMIT.state_DataSend [2] | \iXMIT.state_DataSend [1]);
  assign _038_ = _016_ & _037_;
  assign _039_ = _036_ & _038_;
  assign _040_ = ~(_014_ & _039_);
  assign _011_ = ~(_034_ & _040_);
  assign _041_ = \iRECEIVER.recd_bitCntrH [1] & \iRECEIVER.recd_bitCntrH [0];
  assign _042_ = ~(\iRECEIVER.recd_bitCntrH [2] & _041_);
  assign _043_ = \iRECEIVER.recd_bitCntrH [2] | _041_;
  assign _044_ = \iRECEIVER.countH  & _043_;
  assign _007_ = _042_ & _044_;
  assign _045_ = ~(\iRECEIVER.recd_bitCntrH [1] | \iRECEIVER.recd_bitCntrH [0]);
  assign _046_ = ~(_041_ | _045_);
  assign _006_ = \iRECEIVER.countH  & _046_;
  assign _005_ = \iRECEIVER.countH  & ~(\iRECEIVER.recd_bitCntrH [0]);
  assign _047_ = _101_ & ~(\iRECEIVER.state [2]);
  assign _048_ = ~(_093_ | _047_);
  assign _049_ = \iRECEIVER.rec_datH  | _048_;
  assign _050_ = _099_ | ~(_100_);
  assign _051_ = _093_ & ~(_091_);
  assign _052_ = ~(\iRECEIVER.countH  | _051_);
  assign _053_ = _049_ & _052_;
  assign \iRECEIVER.next_state [1] = ~(_050_ & _053_);
  assign _054_ = xmit_dataH[7] & ~(xmit_dataH[0]);
  assign _055_ = _054_ & ~(xmit_dataH[4]);
  assign _056_ = xmit_dataH[5] & xmit_dataH[3];
  assign _057_ = ~(\iXMIT.state_DataSend [1] | \iXMIT.state_DataSend [0]);
  assign _058_ = _056_ & _057_;
  assign _059_ = _109_ & _024_;
  assign _060_ = _058_ & _059_;
  assign _061_ = ~(_055_ & _060_);
  assign _010_ = ~(_034_ & _061_);
  assign _062_ = \iRECEIVER.rec_datH  | \iRECEIVER.state [2];
  assign \iRECEIVER.rec_readyInH  = _101_ & _062_;
  assign _063_ = _050_ & ~(\iRECEIVER.rec_readyInH );
  assign _064_ = \iRECEIVER.recd_bitCntrH [3] & ~(\iRECEIVER.recd_bitCntrH [2]);
  assign _065_ = _045_ & _064_;
  assign _066_ = ~(_100_ & _065_);
  assign _067_ = _063_ & _066_;
  assign \iRECEIVER.next_state [0] = ~(_096_ & _067_);
  assign _068_ = \iRECEIVER.rec_datH  & _047_;
  assign _009_ = \iRECEIVER.countH  | _068_;
  assign _069_ = ~(\iRECEIVER.recd_bitCntrH [3] ^ _042_);
  assign _008_ = \iRECEIVER.countH  & _069_;
  assign _070_ = ~(\iRECEIVER.bitCell_cntrH [3] ^ _105_);
  assign _004_ = _103_ & _070_;
  assign \iXMIT.xmit_doneInH  = _075_ & ~(xmitH);
  assign _071_ = \iXMIT.state [2] ? \iXMIT.state [0] : _074_;
  assign uart_XMIT_dataH = _080_ & _071_;
  assign _072_ = _073_ | _085_;
  assign \iXMIT.next_state [2] = ~(_088_ & _072_);
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [7] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [7] <= \iRECEIVER.rec_datH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:48.1-55.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_datH  <= 1'h1;
    else \iRECEIVER.rec_datH  <= \iRECEIVER.rec_datSyncH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:80.1-82.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [0] <= 1'h1;
    else \iRECEIVER.state [0] <= \iRECEIVER.next_state [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:80.1-82.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [1] <= 1'h0;
    else \iRECEIVER.state [1] <= \iRECEIVER.next_state [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:80.1-82.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [2] <= 1'h0;
    else \iRECEIVER.state [2] <= \iRECEIVER.next_state [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:72.1-75.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [0] <= 1'h0;
    else if (_009_) \iRECEIVER.recd_bitCntrH [0] <= _005_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:72.1-75.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [1] <= 1'h0;
    else if (_009_) \iRECEIVER.recd_bitCntrH [1] <= _006_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:72.1-75.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [2] <= 1'h0;
    else if (_009_) \iRECEIVER.recd_bitCntrH [2] <= _007_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:72.1-75.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [3] <= 1'h0;
    else if (_009_) \iRECEIVER.recd_bitCntrH [3] <= _008_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [0] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [0] <= \iRECEIVER.par_dataH [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [1] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [1] <= \iRECEIVER.par_dataH [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [2] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [2] <= \iRECEIVER.par_dataH [3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [3] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [3] <= \iRECEIVER.par_dataH [4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [4] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [4] <= \iRECEIVER.par_dataH [5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [5] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [5] <= \iRECEIVER.par_dataH [6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:64.1-69.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [6] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [6] <= \iRECEIVER.par_dataH [7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:58.1-61.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [0] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [0] <= _001_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:58.1-61.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [1] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [1] <= _002_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:58.1-61.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [2] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [2] <= _003_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:58.1-61.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [3] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [3] <= _004_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:48.1-55.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_datSyncH  <= 1'h1;
    else \iRECEIVER.rec_datSyncH  <= uart_REC_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:189.3-191.59" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.DataSend_ena  <= 1'h0;
    else if (_013_) \iXMIT.DataSend_ena  <= 1'h1;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:76.1-78.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [0] <= 1'h0;
    else \iXMIT.state [0] <= \iXMIT.next_state [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:76.1-78.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [1] <= 1'h0;
    else \iXMIT.state [1] <= \iXMIT.next_state [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:76.1-78.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [2] <= 1'h0;
    else \iXMIT.state [2] <= \iXMIT.next_state [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:193.3-230.6" *)
  always @(posedge xmitH, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state_DataSend [0] <= 1'h0;
    else if (_000_) \iXMIT.state_DataSend [0] <= _010_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:193.3-230.6" *)
  always @(posedge xmitH, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state_DataSend [1] <= 1'h0;
    else if (_000_) \iXMIT.state_DataSend [1] <= _011_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:193.3-230.6" *)
  always @(posedge xmitH, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state_DataSend [2] <= 1'h0;
    else if (_000_) \iXMIT.state_DataSend [2] <= _012_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_xmit.v:235.1-237.35" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.xmit_doneH  <= 1'h0;
    else \iXMIT.xmit_doneH  <= \iXMIT.xmit_doneInH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:80.1-87.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[0] <= 1'h0;
    else rec_dataH_temp[0] <= \iRECEIVER.par_dataH [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:80.1-87.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[1] <= 1'h0;
    else rec_dataH_temp[1] <= \iRECEIVER.par_dataH [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:80.1-87.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[2] <= 1'h0;
    else rec_dataH_temp[2] <= \iRECEIVER.par_dataH [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:80.1-87.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[3] <= 1'h0;
    else rec_dataH_temp[3] <= \iRECEIVER.par_dataH [3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:80.1-87.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[4] <= 1'h0;
    else rec_dataH_temp[4] <= \iRECEIVER.par_dataH [4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:80.1-87.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[5] <= 1'h0;
    else rec_dataH_temp[5] <= \iRECEIVER.par_dataH [5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:80.1-87.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[6] <= 1'h0;
    else rec_dataH_temp[6] <= \iRECEIVER.par_dataH [6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:80.1-87.6" *)
  always @(posedge \iRECEIVER.rec_readyH , negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[7] <= 1'h0;
    else rec_dataH_temp[7] <= \iRECEIVER.par_dataH [7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:70.1-77.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[0] <= 1'h0;
    else rec_dataH[0] <= rec_dataH_temp[0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:70.1-77.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[1] <= 1'h0;
    else rec_dataH[1] <= rec_dataH_temp[1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:70.1-77.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[2] <= 1'h0;
    else rec_dataH[2] <= rec_dataH_temp[2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:70.1-77.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[3] <= 1'h0;
    else rec_dataH[3] <= rec_dataH_temp[3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:70.1-77.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[4] <= 1'h0;
    else rec_dataH[4] <= rec_dataH_temp[4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:70.1-77.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[5] <= 1'h0;
    else rec_dataH[5] <= rec_dataH_temp[5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:70.1-77.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[6] <= 1'h0;
    else rec_dataH[6] <= rec_dataH_temp[6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\uart.v:70.1-77.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[7] <= 1'h0;
    else rec_dataH[7] <= rec_dataH_temp[7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmp6g7qno7a\\u_rec.v:158.1-160.35" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_readyH  <= 1'h0;
    else \iRECEIVER.rec_readyH  <= \iRECEIVER.rec_readyInH ;
  assign \iRECEIVER.sys_rst_l  = sys_rst_l;
  assign \iRECEIVER.sys_clk  = sys_clk;
  assign \iRECEIVER.uart_dataH  = uart_REC_dataH;
  assign \iRECEIVER.rec_dataH  = \iRECEIVER.par_dataH ;
  assign \iRECEIVER.shiftH  = \iRECEIVER.countH ;
  assign \iXMIT.sys_clk  = sys_clk;
  assign \iXMIT.sys_rst_l  = sys_rst_l;
  assign \iXMIT.uart_xmitH  = uart_XMIT_dataH;
  assign \iXMIT.xmitH  = xmitH;
  assign \iXMIT.xmit_dataH  = xmit_dataH;
  assign \iXMIT.bitCell_cntrH  = 4'h0;
  assign \iXMIT.xmit_ShiftRegH  = 8'h00;
  assign \iXMIT.bitCountH  = 4'h0;
  assign rec_dataH_rec = \iRECEIVER.par_dataH ;
  assign rec_readyH = \iRECEIVER.rec_readyH ;
  assign xmit_doneH = \iXMIT.xmit_doneH ;
endmodule
