/* Generated by Yosys 0.66+105 (git sha1 72f6df873, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* keep =  1  *)
(* top =  1  *)
(* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:3.1-78.10" *)
module uart(sys_clk, sys_rst_l, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:17.9-17.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:18.9-18.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:19.10-19.25" *)
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:20.9-20.14" *)
  input xmitH;
  wire xmitH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:21.13-21.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:22.10-22.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:24.9-24.23" *)
  input uart_REC_dataH;
  wire uart_REC_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:25.14-25.23" *)
  output [7:0] rec_dataH;
  reg [7:0] rec_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:26.10-26.20" *)
  output rec_readyH;
  wire rec_readyH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:62.1-65.43" *)
  wire _000_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:62.1-65.43" *)
  wire _001_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:62.1-65.43" *)
  wire _002_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:62.1-65.43" *)
  wire _003_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:76.1-79.42" *)
  wire _004_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:76.1-79.42" *)
  wire _005_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:76.1-79.42" *)
  wire _006_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:76.1-79.42" *)
  wire _007_;
  wire _008_;
  wire _009_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:117.14-117.43" *)
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  (* hdlname = "iRECEIVER bitCell_cntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:32.12-32.25" *)
  reg [3:0] \iRECEIVER.bitCell_cntrH ;
  (* hdlname = "iRECEIVER countH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:37.8-37.14" *)
  wire \iRECEIVER.countH ;
  (* hdlname = "iRECEIVER ena" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:44.5-44.8" *)
  reg \iRECEIVER.ena  = 1'h0;
  (* hdlname = "iRECEIVER next_state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:30.12-30.22" *)
  wire [2:0] \iRECEIVER.next_state ;
  (* hdlname = "iRECEIVER par_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:34.12-34.21" *)
  reg [7:0] \iRECEIVER.par_dataH ;
  (* hdlname = "iRECEIVER rec_datH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:31.8-31.16" *)
  reg \iRECEIVER.rec_datH ;
  (* hdlname = "iRECEIVER rec_datSyncH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:31.18-31.30" *)
  reg \iRECEIVER.rec_datSyncH ;
  (* hdlname = "iRECEIVER rec_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:25.14-25.23" *)
  wire [7:0] \iRECEIVER.rec_dataH ;
  (* hdlname = "iRECEIVER rec_readyH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:26.10-26.20" *)
  wire \iRECEIVER.rec_readyH ;
  (* hdlname = "iRECEIVER rec_readyH_temp" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:39.8-39.23" *)
  reg \iRECEIVER.rec_readyH_temp ;
  (* hdlname = "iRECEIVER rec_readyInH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:40.8-40.20" *)
  wire \iRECEIVER.rec_readyInH ;
  (* hdlname = "iRECEIVER recd_bitCntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:36.12-36.25" *)
  reg [3:0] \iRECEIVER.recd_bitCntrH ;
  (* hdlname = "iRECEIVER shiftH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:35.8-35.14" *)
  wire \iRECEIVER.shiftH ;
  (* hdlname = "iRECEIVER state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:30.24-30.29" *)
  reg [2:0] \iRECEIVER.state ;
  (* hdlname = "iRECEIVER sys_clk" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:21.9-21.16" *)
  wire \iRECEIVER.sys_clk ;
  (* hdlname = "iRECEIVER sys_rst_l" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:20.9-20.18" *)
  wire \iRECEIVER.sys_rst_l ;
  (* hdlname = "iRECEIVER uart_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:23.9-23.19" *)
  wire \iRECEIVER.uart_dataH ;
  (* hdlname = "iXMIT bitCell_cntrH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:27.12-27.25" *)
  wire [3:0] \iXMIT.bitCell_cntrH ;
  (* hdlname = "iXMIT bitCountH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:30.12-30.21" *)
  wire [3:0] \iXMIT.bitCountH ;
  (* hdlname = "iXMIT next_state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:24.12-24.22" *)
  wire [2:0] \iXMIT.next_state ;
  (* hdlname = "iXMIT state" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:24.24-24.29" *)
  reg [2:0] \iXMIT.state ;
  (* hdlname = "iXMIT sys_clk" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:15.9-15.16" *)
  wire \iXMIT.sys_clk ;
  (* hdlname = "iXMIT sys_rst_l" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:16.9-16.18" *)
  wire \iXMIT.sys_rst_l ;
  (* hdlname = "iXMIT uart_xmitH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:17.10-17.20" *)
  wire \iXMIT.uart_xmitH ;
  (* hdlname = "iXMIT xmitH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:18.9-18.14" *)
  wire \iXMIT.xmitH ;
  (* hdlname = "iXMIT xmit_ShiftRegH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:29.12-29.26" *)
  wire [7:0] \iXMIT.xmit_ShiftRegH ;
  (* hdlname = "iXMIT xmit_dataH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:19.13-19.23" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \iXMIT.xmit_dataH ;
  (* hdlname = "iXMIT xmit_doneH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:20.10-20.20" *)
  reg \iXMIT.xmit_doneH ;
  (* hdlname = "iXMIT xmit_doneInH" *)
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:35.8-35.20" *)
  wire \iXMIT.xmit_doneInH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:30.17-30.30" *)
  wire [7:0] rec_dataH_rec;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:29.17-29.31" *)
  reg [7:0] rec_dataH_temp;
  assign _025_ = ~\iXMIT.state [1];
  assign _026_ = ~\iXMIT.state [2];
  assign _027_ = \iRECEIVER.state [2] & ~(\iRECEIVER.state [1]);
  assign \iRECEIVER.countH  = _027_ & ~(\iRECEIVER.state [0]);
  assign _028_ = \iRECEIVER.bitCell_cntrH [2] & \iRECEIVER.bitCell_cntrH [1];
  assign _029_ = \iRECEIVER.bitCell_cntrH [3] & ~(\iRECEIVER.bitCell_cntrH [0]);
  assign _030_ = _028_ & _029_;
  assign _031_ = \iRECEIVER.state [1] & ~(\iRECEIVER.state [2]);
  assign _032_ = \iRECEIVER.state [0] & _031_;
  assign _033_ = _032_ & ~(_030_);
  assign _034_ = ~(\iRECEIVER.countH  | _033_);
  assign _035_ = _031_ & ~(\iRECEIVER.state [0]);
  assign _036_ = \iRECEIVER.state [0] & ~(\iRECEIVER.state [1]);
  assign _037_ = _036_ & ~(\iRECEIVER.state [2]);
  assign _038_ = _037_ & ~(\iRECEIVER.rec_datH );
  assign _039_ = _035_ | _038_;
  assign _040_ = ~(\iRECEIVER.bitCell_cntrH [1] | \iRECEIVER.bitCell_cntrH [0]);
  assign _041_ = \iRECEIVER.bitCell_cntrH [2] & ~(\iRECEIVER.bitCell_cntrH [3]);
  assign _042_ = _040_ & _041_;
  assign _043_ = ~(\iRECEIVER.rec_datH  & _042_);
  assign _044_ = ~(_039_ & _043_);
  assign \iRECEIVER.next_state [1] = ~(_034_ & _044_);
  assign _045_ = _035_ & _042_;
  assign _046_ = ~(_035_ & _042_);
  assign _047_ = \iRECEIVER.state [2] | \iRECEIVER.rec_datH ;
  assign \iRECEIVER.rec_readyInH  = _036_ & _047_;
  assign _048_ = _046_ & ~(\iRECEIVER.rec_readyInH );
  assign _049_ = ~(\iRECEIVER.recd_bitCntrH [0] | \iRECEIVER.recd_bitCntrH [1]);
  assign _050_ = \iRECEIVER.recd_bitCntrH [3] & ~(\iRECEIVER.recd_bitCntrH [2]);
  assign _051_ = _049_ & _050_;
  assign _052_ = ~(_032_ & _051_);
  assign _053_ = _048_ & _052_;
  assign \iRECEIVER.next_state [0] = ~(_034_ & _053_);
  assign _054_ = ~(\iXMIT.state [0] | \iXMIT.state [2]);
  assign _055_ = \iXMIT.state [0] & \iXMIT.state [1];
  assign \iXMIT.next_state [0] = \iXMIT.state [2] ? _025_ : _055_;
  assign \iRECEIVER.next_state [2] = _030_ & _032_;
  assign _056_ = ~(_027_ | _036_);
  assign _057_ = _046_ & _056_;
  assign _058_ = _057_ & ~(\iRECEIVER.next_state [2]);
  assign _059_ = \iRECEIVER.bitCell_cntrH [1] & \iRECEIVER.bitCell_cntrH [0];
  assign _060_ = ~(\iRECEIVER.bitCell_cntrH [2] & _059_);
  assign _061_ = \iRECEIVER.bitCell_cntrH [2] ^ _059_;
  assign _002_ = _058_ & _061_;
  assign _011_ = ~(_040_ | _059_);
  assign _001_ = _058_ & _011_;
  assign _000_ = _058_ & ~(\iRECEIVER.bitCell_cntrH [0]);
  assign _012_ = \iRECEIVER.recd_bitCntrH [0] & \iRECEIVER.recd_bitCntrH [1];
  assign _013_ = ~(\iRECEIVER.recd_bitCntrH [2] & _012_);
  assign _014_ = \iRECEIVER.recd_bitCntrH [2] | _012_;
  assign _015_ = \iRECEIVER.countH  & _014_;
  assign _006_ = _013_ & _015_;
  assign _016_ = ~(_049_ | _012_);
  assign _005_ = \iRECEIVER.countH  & _016_;
  assign _004_ = \iRECEIVER.countH  & ~(\iRECEIVER.recd_bitCntrH [0]);
  assign \iRECEIVER.rec_dataH [6] = \iRECEIVER.par_dataH [6] & ~(\iRECEIVER.ena );
  assign \iRECEIVER.rec_dataH [5] = \iRECEIVER.par_dataH [5] & ~(\iRECEIVER.ena );
  assign \iRECEIVER.rec_dataH [4] = \iRECEIVER.par_dataH [4] & ~(\iRECEIVER.ena );
  assign \iRECEIVER.rec_dataH [3] = \iRECEIVER.par_dataH [3] & ~(\iRECEIVER.ena );
  assign \iRECEIVER.rec_dataH [2] = \iRECEIVER.par_dataH [2] & ~(\iRECEIVER.ena );
  assign \iRECEIVER.rec_dataH [1] = \iRECEIVER.par_dataH [1] & ~(\iRECEIVER.ena );
  assign \iRECEIVER.rec_dataH [0] = \iRECEIVER.par_dataH [0] & ~(\iRECEIVER.ena );
  assign rec_readyH = \iRECEIVER.rec_readyH_temp  & ~(\iRECEIVER.ena );
  assign _017_ = \iRECEIVER.rec_datH  & _037_;
  assign _008_ = \iRECEIVER.countH  | _017_;
  assign _018_ = ~(\iXMIT.state [2] | xmitH);
  assign _019_ = \iXMIT.state [0] & ~(\iXMIT.state [1]);
  assign _020_ = ~(\iXMIT.state [0] | _018_);
  assign \iXMIT.next_state [1] = \iXMIT.state [1] ? _026_ : _020_;
  assign _021_ = \iRECEIVER.rec_datH  & ~(\iRECEIVER.ena );
  assign _009_ = ~(_045_ & _021_);
  assign _010_ = ~_009_;
  assign _022_ = ~(\iRECEIVER.recd_bitCntrH [3] ^ _013_);
  assign _007_ = \iRECEIVER.countH  & _022_;
  assign _023_ = ~(\iRECEIVER.bitCell_cntrH [3] ^ _060_);
  assign _003_ = _058_ & _023_;
  assign \iXMIT.next_state [2] = \iXMIT.state [2] & _019_;
  assign _024_ = _025_ & _054_;
  assign uart_XMIT_dataH = \iXMIT.next_state [2] | _024_;
  assign \iXMIT.xmit_doneInH  = _024_ & ~(xmitH);
  assign \iRECEIVER.rec_dataH [7] = \iRECEIVER.par_dataH [7] & ~(\iRECEIVER.ena );
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:173.1-175.35" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.xmit_doneH  <= 1'h0;
    else \iXMIT.xmit_doneH  <= \iXMIT.xmit_doneInH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:73.1-75.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [0] <= 1'h0;
    else \iXMIT.state [0] <= \iXMIT.next_state [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:73.1-75.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [1] <= 1'h0;
    else \iXMIT.state [1] <= \iXMIT.next_state [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_xmit.v:73.1-75.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iXMIT.state [2] <= 1'h0;
    else \iXMIT.state [2] <= \iXMIT.next_state [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:69.1-76.6" *)
  always @(posedge rec_readyH, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[0] <= 1'h0;
    else rec_dataH_temp[0] <= \iRECEIVER.rec_dataH [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:69.1-76.6" *)
  always @(posedge rec_readyH, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[1] <= 1'h0;
    else rec_dataH_temp[1] <= \iRECEIVER.rec_dataH [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:69.1-76.6" *)
  always @(posedge rec_readyH, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[2] <= 1'h0;
    else rec_dataH_temp[2] <= \iRECEIVER.rec_dataH [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:69.1-76.6" *)
  always @(posedge rec_readyH, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[3] <= 1'h0;
    else rec_dataH_temp[3] <= \iRECEIVER.rec_dataH [3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:69.1-76.6" *)
  always @(posedge rec_readyH, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[4] <= 1'h0;
    else rec_dataH_temp[4] <= \iRECEIVER.rec_dataH [4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:69.1-76.6" *)
  always @(posedge rec_readyH, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[5] <= 1'h0;
    else rec_dataH_temp[5] <= \iRECEIVER.rec_dataH [5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:69.1-76.6" *)
  always @(posedge rec_readyH, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[6] <= 1'h0;
    else rec_dataH_temp[6] <= \iRECEIVER.rec_dataH [6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:69.1-76.6" *)
  always @(posedge rec_readyH, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH_temp[7] <= 1'h0;
    else rec_dataH_temp[7] <= \iRECEIVER.rec_dataH [7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[0] <= 1'h0;
    else rec_dataH[0] <= rec_dataH_temp[0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[1] <= 1'h0;
    else rec_dataH[1] <= rec_dataH_temp[1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[2] <= 1'h0;
    else rec_dataH[2] <= rec_dataH_temp[2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[3] <= 1'h0;
    else rec_dataH[3] <= rec_dataH_temp[3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[4] <= 1'h0;
    else rec_dataH[4] <= rec_dataH_temp[4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[5] <= 1'h0;
    else rec_dataH[5] <= rec_dataH_temp[5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[6] <= 1'h0;
    else rec_dataH[6] <= rec_dataH_temp[6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\uart.v:59.1-66.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) rec_dataH[7] <= 1'h0;
    else rec_dataH[7] <= rec_dataH_temp[7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:89.1-165.4" *)
  always @*
    if (!_009_) \iRECEIVER.ena  = 1'h1;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:52.1-59.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_datH  <= 1'h1;
    else \iRECEIVER.rec_datH  <= \iRECEIVER.rec_datSyncH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:68.1-73.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [0] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [0] <= \iRECEIVER.par_dataH [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:68.1-73.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [1] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [1] <= \iRECEIVER.par_dataH [2];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:68.1-73.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [2] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [2] <= \iRECEIVER.par_dataH [3];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:68.1-73.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [3] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [3] <= \iRECEIVER.par_dataH [4];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:68.1-73.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [4] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [4] <= \iRECEIVER.par_dataH [5];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:68.1-73.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [5] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [5] <= \iRECEIVER.par_dataH [6];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:68.1-73.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [6] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [6] <= \iRECEIVER.par_dataH [7];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:168.1-170.40" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_readyH_temp  <= 1'h0;
    else \iRECEIVER.rec_readyH_temp  <= \iRECEIVER.rec_readyInH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:62.1-65.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [0] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [0] <= _000_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:62.1-65.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [1] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [1] <= _001_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:62.1-65.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [2] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [2] <= _002_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:62.1-65.43" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.bitCell_cntrH [3] <= 1'h0;
    else \iRECEIVER.bitCell_cntrH [3] <= _003_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:76.1-79.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [0] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [0] <= _004_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:76.1-79.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [1] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [1] <= _005_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:76.1-79.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [2] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [2] <= _006_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:76.1-79.42" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.recd_bitCntrH [3] <= 1'h0;
    else if (_008_) \iRECEIVER.recd_bitCntrH [3] <= _007_;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:68.1-73.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.par_dataH [7] <= 1'h0;
    else if (\iRECEIVER.countH ) \iRECEIVER.par_dataH [7] <= \iRECEIVER.rec_datH ;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:52.1-59.6" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.rec_datSyncH  <= 1'h1;
    else \iRECEIVER.rec_datSyncH  <= uart_REC_dataH;
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:84.1-86.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [0] <= 1'h1;
    else \iRECEIVER.state [0] <= \iRECEIVER.next_state [0];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:84.1-86.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [1] <= 1'h0;
    else \iRECEIVER.state [1] <= \iRECEIVER.next_state [1];
  (* src = "C:\\Users\\saher\\AppData\\Local\\Temp\\tmpxkc5y0xj\\u_rec.v:84.1-86.28" *)
  always @(posedge sys_clk, negedge sys_rst_l)
    if (!sys_rst_l) \iRECEIVER.state [2] <= 1'h0;
    else \iRECEIVER.state [2] <= \iRECEIVER.next_state [2];
  always @*
    if (_010_)
      $write("Trojan Activated\n");
  assign \iRECEIVER.sys_rst_l  = sys_rst_l;
  assign \iRECEIVER.sys_clk  = sys_clk;
  assign \iRECEIVER.uart_dataH  = uart_REC_dataH;
  assign \iRECEIVER.rec_readyH  = rec_readyH;
  assign \iRECEIVER.shiftH  = \iRECEIVER.countH ;
  assign \iXMIT.sys_clk  = sys_clk;
  assign \iXMIT.sys_rst_l  = sys_rst_l;
  assign \iXMIT.uart_xmitH  = uart_XMIT_dataH;
  assign \iXMIT.xmitH  = xmitH;
  assign \iXMIT.xmit_dataH  = xmit_dataH;
  assign \iXMIT.bitCell_cntrH  = 4'h0;
  assign \iXMIT.xmit_ShiftRegH  = 8'h00;
  assign \iXMIT.bitCountH  = 4'h0;
  assign rec_dataH_rec = \iRECEIVER.rec_dataH ;
  assign xmit_doneH = \iXMIT.xmit_doneH ;
endmodule
